# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]
docs_dir = "docs"
site_author = "https://github.com/stichbury"
site_description = "A reproduction for issue #193."
site_name = "Vizro reproduction"

[[project.markdown_extensions.pymdownx.superfences.custom_fences]]
class = "highlight"
format = {function = "mkdocs_pycafe.formatter", kwds = {type = "vizro", requirements = "vizro==0.1.49"}}
name = "python"
validator = "mkdocs_pycafe.validator"

[project.theme]
language = "en"
