# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]

site_name = "Vizro reproduction"

site_description = "A reproduction for issue #193."

site_author = "https://github.com/stichbury"

docs_dir = "docs"

[project.theme]

language = "en"


[[project.markdown_extensions.pymdownx.superfences.custom_fences]]
name = "python"
class = "highlight"
validator = "mkdocs_pycafe.validator"
format = { function = "mkdocs_pycafe.formatter", kwds = { type = "vizro", requirements = "vizro==0.1.49" } }
